[build]
  publish = "_site/"
  command = "rake build"

[build.environment]
  JEKYLL_ENV = "production"

[[redirects]]
from = "/expertise"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/values"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/expertise/design"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/expertise/development"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/expertise/digital-strategy"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/expertise/engagement-tools"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/expertise/index.html"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/expertise/design/index.html"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/expertise/development/index.html"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/expertise/digital-strategy/index.html"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/expertise/engagement-tools/index.html"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/services/design"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/services/development"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/services/digital-strategy"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/services/digital-ecosystem"
to = "/services/"
status = 301
force = false

[[redirects]]
from = "/blog/feed"
to = "/rss.xml"
status = 301
force = false

[[redirects]]
from = "/taxonomy/term/21/all/feed"
to = "/blog/category/drupal-planet/rss.xml"
status = 301
force = false

[[redirects]]
from = "/portfolio"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/home"
to = "/"
status = 301
force = false

[[redirects]]
from = "/case-study/distribution-hosting-with-pantheon"
to = "/blog/2013/08/distribution-hosting-with-pantheon/"
status = 301
force = false

[[redirects]]
from = "/portfolio/los-angeles-conservancy"
to = "/work/la-conservancy/"
status = 301
force = false

[[redirects]]
from = "/portfolio/portland-design-works"
to = "/work/ridepdw/"
status = 301
force = false

[[redirects]]
from = "/portfolio/environmental-defense-fund"
to = "/work/edf/"
status = 301
force = false

[[redirects]]
from = "/portfolio/salmon-project"
to = "/work/the-salmon-project/"
status = 301
force = false

[[redirects]]
from = "/portfolio/mailchimp"
to = "/work/mailchimp/"
status = 301
force = false




[[redirects]]
from = "/work/coloradotrust/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/edf/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/facing-history/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/families-usa/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/feedingtexas/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/fip-tracker/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/giving-forum/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/hsus-changeforanimals/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/la-conservancy/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/lemelson-mit/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/mailchimp/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/mercy-corps-micromentor/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/MIUSA/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/ncyl/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/oceanoutcomes/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/ridepdw/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/splc-selma/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/the-interwine/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/the-salmon-project/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/travel-portland/"
to = "/work/"
status = 301
force = false

[[redirects]]
from = "/work/wwf/"
to = "/work/"
status = 301
force = false



[[redirects]]
from = "/blog/sean"
to = "/team/sean/"
status = 301
force = false

[[redirects]]
from = "/blog/lev"
to = "/team/lev/"
status = 301
force = false

[[redirects]]
from = "/blog/betsy"
to = "/team/betsy/"
status = 301
force = false

[[redirects]]
from = "/blog/category/drupal-planet"
to = "/blog/category/drupal-planet/"
status = 301
force = false

[[redirects]]
from = "/expertise/content-strategy"
to = "/services/digital-strategy/"
status = 301
force = false

[[redirects]]
from = "/engage"
to = "/services/"
status = 301
force = false

# Old site redirects
[[redirects]]
from = "/sites/default/files/*"
to = "/assets/images/old_site/:splat"
status = 301
force = false
